"""add_nickname_to_buildings

Revision ID: 1cd30b751180
Revises: b6f28c1d631f
Create Date: 2026-02-19 09:03:57.279072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd30b751180'
down_revision: Union[str, Sequence[str], None] = 'b6f28c1d631f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('nickname', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'buildings', ['nickname'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'buildings', type_='unique')
    op.drop_column('buildings', 'nickname')
    # ### end Alembic commands ###
