"""initial

Revision ID: 63885f656acb
Revises: 
Create Date: 2026-01-22 07:58:30.896173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63885f656acb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_lots',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('total_spaces', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permit_types',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lot_permit_access',
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('permit_id', sa.UUID(), nullable=False),
    sa.Column('days_of_week', postgresql.ARRAY(sa.INTEGER()), nullable=True),
    sa.Column('access_start', sa.Time(), nullable=True),
    sa.Column('access_end', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['parking_lots.id'], ),
    sa.ForeignKeyConstraint(['permit_id'], ['permit_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id', 'permit_id', 'days_of_week', 'access_start', name='uq_lot_permit_days_start')
    )
    op.create_table('parking_snapshots',
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('free_spaces', sa.Integer(), nullable=False),
    sa.Column('occupancy_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['parking_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshots_lot_time', 'parking_snapshots', ['lot_id', sa.literal_column('collected_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_snapshots_lot_time', table_name='parking_snapshots')
    op.drop_table('parking_snapshots')
    op.drop_table('lot_permit_access')
    op.drop_table('permit_types')
    op.drop_table('parking_lots')
    # ### end Alembic commands ###
