"""add_parking_forecasts

Revision ID: 6e390f037587
Revises: 84fa3950747c
Create Date: 2026-03-02 15:34:09.049706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e390f037587'
down_revision: Union[str, Sequence[str], None] = '84fa3950747c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_forecasts',
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('forecast_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_free_spaces', sa.Integer(), nullable=False),
    sa.Column('predicted_free_spaces_lower', sa.Integer(), nullable=False),
    sa.Column('predicted_occupancy_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['parking_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_forecasts_lot_time', 'parking_forecasts', ['lot_id', 'forecast_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_forecasts_lot_time', table_name='parking_forecasts')
    op.drop_table('parking_forecasts')
    # ### end Alembic commands ###
