"""add_lot_building_distances

Revision ID: 84fa3950747c
Revises: 1cd30b751180
Create Date: 2026-02-19 17:06:43.060573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84fa3950747c'
down_revision: Union[str, Sequence[str], None] = '1cd30b751180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lot_building_distances',
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('distance_miles', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('duration_minutes', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lot_id'], ['parking_lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id', 'building_id')
    )
    op.create_index(op.f('ix_lot_building_distances_building_id'), 'lot_building_distances', ['building_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lot_building_distances_building_id'), table_name='lot_building_distances')
    op.drop_table('lot_building_distances')
    # ### end Alembic commands ###
