"""add_schedules_buildings_classrooms

Revision ID: b6f28c1d631f
Revises: 301f23cfa54a
Create Date: 2026-01-25 13:17:36.736628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f28c1d631f'
down_revision: Union[str, Sequence[str], None] = '301f23cfa54a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('classrooms',
    sa.Column('location_string', sa.String(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_string')
    )
    op.create_index(op.f('ix_classrooms_building_id'), 'classrooms', ['building_id'], unique=False)
    op.create_table('user_schedules',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_schedules_user_id'), 'user_schedules', ['user_id'], unique=True)
    op.create_table('schedule_events',
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('days_of_week', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['user_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_events_classroom_id'), 'schedule_events', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_schedule_events_schedule_id'), 'schedule_events', ['schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_events_schedule_id'), table_name='schedule_events')
    op.drop_index(op.f('ix_schedule_events_classroom_id'), table_name='schedule_events')
    op.drop_table('schedule_events')
    op.drop_index(op.f('ix_user_schedules_user_id'), table_name='user_schedules')
    op.drop_table('user_schedules')
    op.drop_index(op.f('ix_classrooms_building_id'), table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_table('buildings')
    # ### end Alembic commands ###
